version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 816069135163.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - docker build -t group8-microservice .
      - docker tag group8-microservice:latest 816069135163.dkr.ecr.us-east-2.amazonaws.com/group8-microservice:latest
  post_build:
    commands:
      - docker push 816069135163.dkr.ecr.us-east-2.amazonaws.com/group8-microservice:latest
artifacts:
  files: '**/*'
